### ISSUE TITLE
[Feature Request] Change Response Model 

### ISSUE THREAD

**Issue by bennet-esyoil** [crowdsecurity/lua-cs-bouncer#20]
Currently, the bouncer rejects clients with 403 Forbidden if they are on the decision list. While this is an optimal solution by itself, it takes away some flexibility on how to handle denials.

We currently have the nginx/access.lua script modified to redirect to another page instead of showing a forbidden error. 

My suggestion is to add a new config option "ACTION", which can be "STATUS_CODE" or "REDIRECT" or something else, depending on what someone want's to do. And a variable "REDIRECT_PATH" where the REDIRECT Action would redirect on deny.

All names are obviously just ideas, they could be named however. 

If interested I can contribute this feature.

**Comment by he2ss** [comment]
This has been added in https://github.com/crowdsecurity/lua-cs-bouncer/pull/23
It will be available in the next release of nginx and openresty bouncers.
