### ISSUE TITLE
HTTP2/3 Check request before invoking read_body

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/lua-cs-bouncer#63]
In http2 / http3 ngx.req.read_body() will throw an error if the request does not have a `content-length` header. We should handle this as the lua level before invoking this function.

Either check if the header exists or have a try catch lua function using `pcall`

https://github.com/crowdsecurity/lua-cs-bouncer/blob/26e9c0c19ccb00cd6bae059851cf3c3fb32d8e38/lib/crowdsec.lua#L410

linked to #44

**Comment by Zoey2936** [comment]
when will it be released?

**Comment by blotus** [comment]
I need to merge 1 or 2 other PRs, so probably tomorrow and next week at the latest.
