### ISSUE TITLE
Allow the use of code 444

### ISSUE THREAD

**Issue by dimur** [crowdsecurity/lua-cs-bouncer#72]
Could you add the possibility of using code 444 to reset the connection, which can help save performance during DDoS attack?

I suggest adding this
`M.HTTP_CODE["444"] = ngx.HTTP_CLOSE`
here https://github.com/crowdsecurity/lua-cs-bouncer/blob/ec3885e6f9b6ee46b7cce8359be1265e195ac34d/lib/plugins/crowdsec/utils.lua#L16-L17

**Comment by LaurenceJJones** [comment]
we have merged this, however, the downstream packages like nginx and openresty will not get the latest changes till we do a release. We are going to do a release within the next few weeks to include some metrics improvements which will include this change.
